# Generated by Django 5.0.1 on 2024-01-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='updated_user',
            field=models.DateTimeField(auto_now=True, verbose_name='Date of update'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Last Login'),
        ),
    ]
